# Generated by Django 4.2.2 on 2023-06-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campeonato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                ("nombre_auspiciante", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="CampeonatoEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.IntegerField()),
                (
                    "Campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="futbolec.campeonato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                ("siglas", models.CharField(max_length=10)),
                ("username_twitter", models.CharField(max_length=100, unique=True)),
                (
                    "campeonatos",
                    models.ManyToManyField(
                        through="futbolec.CampeonatoEquipo", to="futbolec.campeonato"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Judador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                ("posicion", models.CharField(max_length=20)),
                ("nro_camiseta", models.IntegerField()),
                ("sueldo", models.FloatField()),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="futbolec.equipo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campeonatoequipo",
            name="Equipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="futbolec.equipo"
            ),
        ),
        migrations.AddField(
            model_name="campeonato",
            name="equipos",
            field=models.ManyToManyField(
                through="futbolec.CampeonatoEquipo", to="futbolec.equipo"
            ),
        ),
    ]
